doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
                charset: utf8mb4
            tenant:
                server_version: "8.0.21"
                driver: pdo_mysql
                host: services-db
                port: 3306
                dbname: ~
                user: ~
                password: ~
                charset: utf8mb4
                wrapper_class: App\Infrastructure\Persistence\Connection\DoctrineTenantConnection

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: true
                mappings:
                    App:
                        is_bundle: false
                        type: xml
                        dir: '%kernel.project_dir%/src/Infrastructure/Persistence/Mapping/Main'
                        prefix: 'App\Domain\Model'
                        alias: App
                dql:
                    string_functions:
                        JSON_EXTRACT: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonExtract
            tenant:
                connection: tenant
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    Tenant:
                        is_bundle: false
                        type: xml
                        dir: '%kernel.project_dir%/src/Infrastructure/Persistence/Mapping/Tenant'
                        prefix: 'App\Domain\Model'
                        alias: Tenant
                filters:
                    softdeleteable:
                        class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                        enabled: true
